export const appUrls = {
  landing: '/',
  login: 'login',
  dashboard: 'dashboard',
  notFound: 'not-found',
  users: 'users',
  userDetails: 'users/:id',
  resetPassword: 'reset-password',
  requestOtp: 'request-otp',
  verifyOtp: 'verify-otp',
  students: 'students',
  studentsDetails: 'students/:id',
  items: 'items',
  order: 'order',
};
